package com.optguard.entity;

public enum DeadlineType {
    STEM_VALIDATION,
    STEM_12_MONTH_EVALUATION,
    STEM_18_MONTH_VALIDATION,
    STEM_FINAL_EVALUATION,
    EAD_EXPIRY_REMINDER,
    OPT_END_REMINDER,
    STEM_END_REMINDER,
    PASSPORT_EXPIRY_REMINDER,
    EMPLOYER_CHANGE_REPORTING,
    ADDRESS_CHANGE_REPORTING
}
